Repository DevCycleHQ/java-server-sdk, pull requests merged in 2023-08, with the labels that each got.

#93 chore: Update wasmtime-java and tweak logs (DVC 8452)
  README.md
  build.gradle
  src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
  src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
  src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
Labels: 1 min review

#94 fix: Mark scheduler threads as daemon so they don't block JVM shutdown
  src/main/java/com/devcycle/sdk/server/local/managers/DaemonThreadFactory.java
  src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
  src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
Labels: 1 min review

#96 chore: update to use the tagged version of the release action instead of main
  .github/workflows/release.yml
Labels: 1 min review

#92 feat!: rename public interfaces from DVC to DevCycle
  README.md
  benchmark/src/main/java/com/devcycle/SDKBenchmark.java
  benchmark/src/main/java/com/devcycle/VariableTest.java
  build.gradle
  docs/DevCycleEvent.md
  docs/DevCycleLocalClient.md
  docs/DevCycleResponse.md
  docs/DevCycleUser.md
  example-cloud/README.md
  example-cloud/gradle/wrapper/gradle-wrapper.properties
  example-cloud/gradlew
  example-cloud/gradlew.bat
  example-cloud/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java
  example-cloud/src/main/resources/application.properties
  example-cloud/src/main/resources/templates/fragments/trackData.html
  example-local/README.md
  example-local/build.gradle
  example-local/gradle/wrapper/gradle-wrapper.properties
  example-local/gradlew
  example-local/gradlew.bat
  example-local/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java
  example-local/src/main/resources/application.properties
  example-local/src/main/resources/templates/fragments/trackData.html
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudApiClient.java
  src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudClient.java
  src/main/java/com/devcycle/sdk/server/cloud/model/DevCycleCloudOptions.java
  src/main/java/com/devcycle/sdk/server/common/api/IDevCycleApi.java
  src/main/java/com/devcycle/sdk/server/common/exception/DevCycleException.java
  src/main/java/com/devcycle/sdk/server/common/logging/DevCycleLogger.java
  src/main/java/com/devcycle/sdk/server/common/logging/IDevCycleLogger.java
  src/main/java/com/devcycle/sdk/server/common/logging/SimpleDevCycleLogger.java
  src/main/java/com/devcycle/sdk/server/common/model/DevCycleEvent.java
  src/main/java/com/devcycle/sdk/server/common/model/DevCycleResponse.java
  src/main/java/com/devcycle/sdk/server/common/model/DevCycleUser.java
  src/main/java/com/devcycle/sdk/server/common/model/DevCycleUserAndEvents.java
  src/main/java/com/devcycle/sdk/server/common/model/IDevCycleOptions.java
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalApiClient.java
  src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalClient.java
  src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalEventsApiClient.java
  src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
  src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
  src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
  src/main/java/com/devcycle/sdk/server/local/model/DevCycleLocalOptions.java
  src/main/java/com/devcycle/sdk/server/local/model/EventPayload.java
  src/main/java/com/devcycle/sdk/server/local/model/FlushPayload.java
  src/main/java/com/devcycle/sdk/server/local/model/RequestEvent.java
  src/main/java/com/devcycle/sdk/server/local/utils/ProtobufUtils.java
  src/test/java/com/devcycle/sdk/server/cloud/DevCycleCloudClientTest.java
  src/test/java/com/devcycle/sdk/server/common/api/DVCApiMock.java
  src/test/java/com/devcycle/sdk/server/helpers/TestResponse.java
  src/test/java/com/devcycle/sdk/server/local/DevCycleLocalClientTest.java
  src/test/java/com/devcycle/sdk/server/local/LocalBucketingTest.java
Labels: 30 min review

#95 ci: Add simplified examples and a workflow to run them on PRs
  .github/workflows/test-examples.yml
  build.gradle
  src/examples/java/com/devcycle/examples/CloudExample.java
  src/examples/java/com/devcycle/examples/LocalExample.java
Labels: 10 min review
