Repository DevCycleHQ/java-server-sdk, pull requests merged in 2023-07, with the labels that each got.

#83 DVC-8003 custom header and ssl support
  src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudApiClient.java
  src/main/java/com/devcycle/sdk/server/cloud/model/DVCCloudOptions.java
  src/main/java/com/devcycle/sdk/server/common/api/APIUtils.java
  src/main/java/com/devcycle/sdk/server/common/api/IRestOptions.java
  src/main/java/com/devcycle/sdk/server/common/interceptor/CustomHeaderInterceptor.java
  src/main/java/com/devcycle/sdk/server/local/api/DVCLocalApiClient.java
  src/main/java/com/devcycle/sdk/server/local/api/DVCLocalEventsApiClient.java
  src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
  src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
  src/test/java/com/devcycle/sdk/server/utils/ByteConversionUtilsTest.java
Labels: 10 min review

#84 Release 1.7.0
  README.md
  benchmark/pom.xml
  build.gradle
  example-cloud/build.gradle
  example-local/build.gradle
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/main/resources/bucketing-lib.release.wasm
  src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
Labels: 1 min review

#85 [fix] Prevent multiple authorization headers in Events API requests
  benchmark/pom.xml
  src/main/java/com/devcycle/sdk/server/common/interceptor/AuthorizationHeaderInterceptor.java
Labels: 1 min review

#87 fix: README.md logging code snippet
  README.md
Labels: 1 min review, safe-changes

#88 feat: Create release action to handle automated releases
  .gitattributes
  .github/workflows/checks.yml
  .github/workflows/release.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
  src/test/java/com/devcycle/sdk/server/helpers/LocalConfigServer.java
  src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
Labels: 5 min review

#89 fix: update release to prevent deploy on draft and prerelease
  .github/workflows/release.yml
Labels: 1 min review

#90 fix: release version regex able to match multi-digit values
  .github/workflows/release.yml
Labels: 1 min review

#91 fix: revised github automated release
  .github/workflows/release.yml
Labels: 5 min review
