Repository DevCycleHQ/java-server-sdk, pull requests merged in 2023-10, with the labels that each got.

#97 fix: Upgrade to wasmtime-java 0.19.0 (DVC 9128)
  README.md
  benchmark/README.md
  benchmark/pom.xml
  build.gradle
  example-cloud/README.md
  example-cloud/build.gradle
  example-cloud/gradle/wrapper/gradle-wrapper.properties
  example-cloud/gradlew
  example-cloud/gradlew.bat
  example-cloud/pom.xml
  example-cloud/settings.gradle
  example-cloud/src/main/java/com/devcycle/example/java/sdk/app/CloudExampleJavaSdkAppApplication.java
  example-cloud/src/main/java/com/devcycle/example/java/sdk/app/configuration/HelloWorldConfiguration.java
  example-cloud/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java
  example-cloud/src/main/resources/application.properties
  example-cloud/src/main/resources/static/css/local.css
  example-cloud/src/main/resources/static/img/togglebot-winking.svg
  example-cloud/src/main/resources/static/img/togglebot.svg
  example-cloud/src/main/resources/templates/fragments/flagData.html
  example-cloud/src/main/resources/templates/fragments/flagDataDetails.html
  example-cloud/src/main/resources/templates/fragments/trackData.html
  example-cloud/src/main/resources/templates/home.html
  example-cloud/src/test/java/com/devcycle/example/java/sdk/app/ExampleJavaSdkAppApplicationTests.java
  example-local/README.md
  example-local/build.gradle
  example-local/gradle/wrapper/gradle-wrapper.properties
  example-local/gradlew
  example-local/gradlew.bat
  example-local/pom.xml
  example-local/settings.gradle
  example-local/src/main/java/com/devcycle/example/java/sdk/app/LocalExampleJavaSdkAppApplication.java
  example-local/src/main/java/com/devcycle/example/java/sdk/app/configuration/HelloWorldConfiguration.java
  example-local/src/main/java/com/devcycle/example/java/sdk/app/controller/HelloWorld.java
  example-local/src/main/resources/application.properties
  example-local/src/main/resources/static/css/local.css
  example-local/src/main/resources/static/img/togglebot-winking.svg
  example-local/src/main/resources/static/img/togglebot.svg
  example-local/src/main/resources/templates/fragments/flagData.html
  example-local/src/main/resources/templates/fragments/flagDataDetails.html
  example-local/src/main/resources/templates/fragments/trackData.html
  example-local/src/main/resources/templates/home.html
  example-local/src/test/java/com/devcycle/example/java/sdk/app/ExampleJavaSdkAppApplicationTests.java
  pom.xml
  src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
Labels: 5 min review

#98 fix: remove version bump commands for deleted example projects (DVC-9242)
  .github/workflows/release.yml
Labels: 1 min review

#99 fix: Remove more references to examples directories (DVC-9244)
  .github/workflows/release.yml
Labels: 1 min review

#100 chore: Dependabot config v1
  .github/dependabot.yml
Labels: 1 min review

#111 feat: Add OpenFeature provider
  .github/workflows/test-examples.yml
  OpenFeature.md
  README.md
  build.gradle
  src/examples/java/com/devcycle/examples/CloudExample.java
  src/examples/java/com/devcycle/examples/LocalExample.java
  src/examples/java/com/devcycle/examples/OpenFeatureExample.java
  src/main/java/com/devcycle/sdk/server/cloud/api/DevCycleCloudClient.java
  src/main/java/com/devcycle/sdk/server/common/api/IDevCycleClient.java
  src/main/java/com/devcycle/sdk/server/common/model/DevCycleUser.java
  src/main/java/com/devcycle/sdk/server/local/api/DevCycleLocalClient.java
  src/main/java/com/devcycle/sdk/server/openfeature/DevCycleProvider.java
  src/test/java/com/devcycle/sdk/server/cloud/DevCycleCloudClientTest.java
  src/test/java/com/devcycle/sdk/server/common/model/DevCycleUserTest.java
  src/test/java/com/devcycle/sdk/server/helpers/MockDevCycleClient.java
  src/test/java/com/devcycle/sdk/server/openfeature/DevCycleProviderLocalSDKTest.java
  src/test/java/com/devcycle/sdk/server/openfeature/DevCycleProviderTest.java
Labels: 30 min review
