Repository DevCycleHQ/java-server-sdk, pull requests merged in 2023-06, with the labels that each got.

#76 Enable GitHub action to run test-harness on PRs
  .github/workflows/run-test-harness.yml
  .github/workflows/unit-test.yml
Labels: 1 min review, safe-changes

#78 DVC-7677 use 4 core actions runner for test harness
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#77 Add customizable logging system
  README.md
  src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java
  src/main/java/com/devcycle/sdk/server/cloud/model/DVCCloudOptions.java
  src/main/java/com/devcycle/sdk/server/common/logging/DVCLogger.java
  src/main/java/com/devcycle/sdk/server/common/logging/IDVCLogger.java
  src/main/java/com/devcycle/sdk/server/common/logging/SimpleDVCLogger.java
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/main/java/com/devcycle/sdk/server/local/api/DVCLocalClient.java
  src/main/java/com/devcycle/sdk/server/local/bucketing/LocalBucketing.java
  src/main/java/com/devcycle/sdk/server/local/managers/EnvironmentConfigManager.java
  src/main/java/com/devcycle/sdk/server/local/managers/EventQueueManager.java
  src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
  src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
Labels: 10 min review

#79 bumping version numbers
  README.md
  benchmark/pom.xml
  build.gradle
  example-cloud/build.gradle
  example-local/build.gradle
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
Labels: 1 min review

#80 Update wasmtime dependency
  README.md
  benchmark/pom.xml
  build.gradle
  example-cloud/build.gradle
  example-local/build.gradle
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
Labels: 1 min review

#81 [fix] Setting custom logger on DVCLocalClient causes exception
  README.md
  src/main/java/com/devcycle/sdk/server/local/model/DVCLocalOptions.java
  src/test/java/com/devcycle/sdk/server/local/DVCLocalClientTest.java
Labels: 1 min review

#82 Release 1.6.2
  README.md
  benchmark/pom.xml
  build.gradle
  example-cloud/build.gradle
  example-local/build.gradle
  src/main/java/com/devcycle/sdk/server/common/model/PlatformData.java
  src/test/java/com/devcycle/sdk/server/cloud/DVCCloudClientTest.java
Labels: 1 min review
